version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./db:/app/db
    restart: always
    environment:
      - TZ=Europe/Paris

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    environment:
      - TZ=Europe/Paris